[2024-11-20T10:33:12.597+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-20T10:33:10.321957+00:00 [queued]>
[2024-11-20T10:33:12.602+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-20T10:33:10.321957+00:00 [queued]>
[2024-11-20T10:33:12.602+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-20T10:33:12.607+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-11-20 10:33:10.321957+00:00
[2024-11-20T10:33:12.610+0000] {standard_task_runner.py:57} INFO - Started process 813 to run task
[2024-11-20T10:33:12.613+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-11-20T10:33:10.321957+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmphjp33qmj']
[2024-11-20T10:33:12.615+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask extract_data_from_wikipedia
[2024-11-20T10:33:12.656+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-20T10:33:10.321957+00:00 [running]> on host scheduler
[2024-11-20T10:33:12.713+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ClarkSon Tech' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T10:33:10.321957+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T10:33:10.321957+00:00'
[2024-11-20T10:33:12.714+0000] {logging_mixin.py:151} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-11-20T10:33:13.206+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 50, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 27, in get_wikipedia_data
    table = soup.find_all("table", {"class": "wikitable sortable"})[0]
IndexError: list index out of range
[2024-11-20T10:33:13.213+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20241120T103310, start_date=20241120T103312, end_date=20241120T103313
[2024-11-20T10:33:13.219+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task extract_data_from_wikipedia (list index out of range; 813)
[2024-11-20T10:33:13.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-20T10:33:13.248+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
