[2024-11-15T08:31:25.219+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-15T08:31:23.274713+00:00 [queued]>
[2024-11-15T08:31:25.223+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-15T08:31:23.274713+00:00 [queued]>
[2024-11-15T08:31:25.223+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-15T08:31:25.229+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-11-15 08:31:23.274713+00:00
[2024-11-15T08:31:25.231+0000] {standard_task_runner.py:57} INFO - Started process 518 to run task
[2024-11-15T08:31:25.233+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-11-15T08:31:23.274713+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmpgsegh4wu']
[2024-11-15T08:31:25.235+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask extract_data_from_wikipedia
[2024-11-15T08:31:25.271+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-11-15T08:31:23.274713+00:00 [running]> on host scheduler
[2024-11-15T08:31:25.323+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Clarkson' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T08:31:23.274713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T08:31:23.274713+00:00'
[2024-11-15T08:31:25.324+0000] {logging_mixin.py:151} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-11-15T08:31:30.189+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 31, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 22, in get_wikipedia_data
    table = soup.find_all("table", {"class": "wikitable sortable sticky-header jquery-tablesorter"})[0]
IndexError: list index out of range
[2024-11-15T08:31:30.202+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20241115T083123, start_date=20241115T083125, end_date=20241115T083130
[2024-11-15T08:31:30.208+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task extract_data_from_wikipedia (list index out of range; 518)
[2024-11-15T08:31:30.218+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-15T08:31:30.231+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
